/*
 * This file is generated by jOOQ.
 */
package ru.saprcorset.backend.adapters.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.saprcorset.backend.adapters.db.jooq.tables.Constructions;
import ru.saprcorset.backend.adapters.db.jooq.tables.Databasechangelog;
import ru.saprcorset.backend.adapters.db.jooq.tables.Databasechangeloglock;
import ru.saprcorset.backend.adapters.db.jooq.tables.Kernels;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.constructions</code>.
     */
    public final Constructions CONSTRUCTIONS = Constructions.CONSTRUCTIONS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.kernels</code>.
     */
    public final Kernels KERNELS = Kernels.KERNELS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.CONSTRUCTIONS_SEQ,
            Sequences.KERNELS_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Constructions.CONSTRUCTIONS,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Kernels.KERNELS
        );
    }
}
