/*
 * This file is generated by jOOQ.
 */
package ru.saprcorset.backend;


import ru.saprcorset.backend.tables.Constructions;
import ru.saprcorset.backend.tables.Databasechangelog;
import ru.saprcorset.backend.tables.Databasechangeloglock;
import ru.saprcorset.backend.tables.Kernels;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.constructions</code>.
     */
    public static final Constructions CONSTRUCTIONS = Constructions.CONSTRUCTIONS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.kernels</code>.
     */
    public static final Kernels KERNELS = Kernels.KERNELS;
}
