server:
  port: 8090
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5990/tmc_db
    password: tmc_docker
    username: tmc_docker
  liquibase:
    change-log: "classpath:db/master.xml"
    enabled: false