server:
  port: 8090
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/selectel
    password: selectel
    username: selectel
  liquibase:
    change-log: "classpath:db/master.xml"
    enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true