/*
 * This file is generated by jOOQ.
 */
package ru.saprcorset.backend.adapters.db.jooq.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.saprcorset.backend.adapters.db.jooq.tables.Kernels;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KernelsRecord extends UpdatableRecordImpl<KernelsRecord> implements Record8<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.kernels.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.kernels.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.kernels.kernel_size</code>.
     */
    public void setKernelSize(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.kernels.kernel_size</code>.
     */
    public BigDecimal getKernelSize() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.kernels.cross_sectional_area</code>.
     */
    public void setCrossSectionalArea(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.kernels.cross_sectional_area</code>.
     */
    public BigDecimal getCrossSectionalArea() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.kernels.elastic_modulus</code>.
     */
    public void setElasticModulus(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.kernels.elastic_modulus</code>.
     */
    public BigDecimal getElasticModulus() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.kernels.allowable_stress</code>.
     */
    public void setAllowableStress(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.kernels.allowable_stress</code>.
     */
    public BigDecimal getAllowableStress() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.kernels.concentrated_load</code>.
     */
    public void setConcentratedLoad(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.kernels.concentrated_load</code>.
     */
    public BigDecimal getConcentratedLoad() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.kernels.linear_voltage</code>.
     */
    public void setLinearVoltage(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.kernels.linear_voltage</code>.
     */
    public BigDecimal getLinearVoltage() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.kernels.constructions_id</code>.
     */
    public void setConstructionsId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.kernels.constructions_id</code>.
     */
    public Integer getConstructionsId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Kernels.KERNELS.ID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return Kernels.KERNELS.KERNEL_SIZE;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Kernels.KERNELS.CROSS_SECTIONAL_AREA;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Kernels.KERNELS.ELASTIC_MODULUS;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Kernels.KERNELS.ALLOWABLE_STRESS;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Kernels.KERNELS.CONCENTRATED_LOAD;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Kernels.KERNELS.LINEAR_VOLTAGE;
    }

    @Override
    public Field<Integer> field8() {
        return Kernels.KERNELS.CONSTRUCTIONS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public BigDecimal component2() {
        return getKernelSize();
    }

    @Override
    public BigDecimal component3() {
        return getCrossSectionalArea();
    }

    @Override
    public BigDecimal component4() {
        return getElasticModulus();
    }

    @Override
    public BigDecimal component5() {
        return getAllowableStress();
    }

    @Override
    public BigDecimal component6() {
        return getConcentratedLoad();
    }

    @Override
    public BigDecimal component7() {
        return getLinearVoltage();
    }

    @Override
    public Integer component8() {
        return getConstructionsId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public BigDecimal value2() {
        return getKernelSize();
    }

    @Override
    public BigDecimal value3() {
        return getCrossSectionalArea();
    }

    @Override
    public BigDecimal value4() {
        return getElasticModulus();
    }

    @Override
    public BigDecimal value5() {
        return getAllowableStress();
    }

    @Override
    public BigDecimal value6() {
        return getConcentratedLoad();
    }

    @Override
    public BigDecimal value7() {
        return getLinearVoltage();
    }

    @Override
    public Integer value8() {
        return getConstructionsId();
    }

    @Override
    public KernelsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public KernelsRecord value2(BigDecimal value) {
        setKernelSize(value);
        return this;
    }

    @Override
    public KernelsRecord value3(BigDecimal value) {
        setCrossSectionalArea(value);
        return this;
    }

    @Override
    public KernelsRecord value4(BigDecimal value) {
        setElasticModulus(value);
        return this;
    }

    @Override
    public KernelsRecord value5(BigDecimal value) {
        setAllowableStress(value);
        return this;
    }

    @Override
    public KernelsRecord value6(BigDecimal value) {
        setConcentratedLoad(value);
        return this;
    }

    @Override
    public KernelsRecord value7(BigDecimal value) {
        setLinearVoltage(value);
        return this;
    }

    @Override
    public KernelsRecord value8(Integer value) {
        setConstructionsId(value);
        return this;
    }

    @Override
    public KernelsRecord values(Integer value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KernelsRecord
     */
    public KernelsRecord() {
        super(Kernels.KERNELS);
    }

    /**
     * Create a detached, initialised KernelsRecord
     */
    public KernelsRecord(Integer id, BigDecimal kernelSize, BigDecimal crossSectionalArea, BigDecimal elasticModulus, BigDecimal allowableStress, BigDecimal concentratedLoad, BigDecimal linearVoltage, Integer constructionsId) {
        super(Kernels.KERNELS);

        setId(id);
        setKernelSize(kernelSize);
        setCrossSectionalArea(crossSectionalArea);
        setElasticModulus(elasticModulus);
        setAllowableStress(allowableStress);
        setConcentratedLoad(concentratedLoad);
        setLinearVoltage(linearVoltage);
        setConstructionsId(constructionsId);
    }
}
